---
title: "Sales Report with Highcharter"
author: "Joshua Kunst"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}
library(highcharter)
library(dplyr)
library(viridisLite)
# library(forecast)
library(treemap)
library(flexdashboard)

thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )

latlong2state <- function(pointsDF) {
    # Prepare SpatialPolygons object with one SpatialPolygon
    # per state (plus DC, minus HI & AK)
    states <- map('state', fill=TRUE, col="transparent", plot=FALSE)
    IDs <- sapply(strsplit(states$names, ":"), function(x) x[1])
    states_sp <- map2SpatialPolygons(states, IDs=IDs,
                     proj4string=CRS("+proj=longlat +datum=WGS84"))

    # Convert pointsDF to a SpatialPoints object 
    pointsSP <- SpatialPoints(pointsDF, 
                    proj4string=CRS("+proj=longlat +datum=WGS84"))

    # Use 'over' to get _indices_ of the Polygons object containing each point 
    indices <- over(pointsSP, states_sp)

    # Return the state names of the Polygons object containing each point
    stateNames <- sapply(states_sp@polygons, function(x) x@ID)
    stateNames[indices]
}
```



```{r init, eval=FALSE,include=FALSE}



latMax = 39.773
latMin = 37.5205
lonMax = -89.149
lonMin = -91.4015


con_in <-
  file("~/Go/src/github.com/rotblauer/tileTester2/test.small.json.gz")
con_out <- file(tmp <- "tmp", open = "wb")
stream_in(
  con_in,
  handler = function(df) {
    # df <- dplyr::filter(df, distance > 1000)
    # df <- dplyr::mutate(df, delta = dep_delay - arr_delay)
    loc = do.call(rbind.data.frame, df$geometry$coordinates)
    colnames(loc) = c("lon", "lat")
    loc$elevation = df$properties$Elevation
    loc$note = df$properties$Notes
    loc$time = df$properties$Time
    loc$unixTime = df$properties$UnixTime
    loc$speed = df$properties$Speed
    loc$pressure = df$properties$Pressure
    loc$activity = df$properties$Activity
    print(colnames(loc))
    colnames(loc) = c(
      "lon",
      "lat",
      "elevation",
      "Notes",
      "Time",
      "UnixTime",
      "Speed",
      "Pressure",
      "Activity"
    )
    loc <- filter(loc, lat < latMax &
                    lat > latMin) %>% filter(lon > lonMin &
                                               lon < lonMax)
    
    
    stream_out(loc, con_out, pagesize = 1000)
  },
  pagesize = 200000
)
close(con_out)
loc <- stream_in(file(tmp), pagesize = 2000000)
loc$state = latlong2state(loc[, c(1, 2)])
# nrow(x)
unlink(tmp)
save(loc, file = "loc.Rdata")

# load("x.Rdata")


```

Column {data-width=600}
-----------------------------------------------------------------------

### Sales Forecast

```{r}
load("loc.Rdata")
latlong2state(loc)
# AirPassengers %>% 
#   forecast(level = 90) %>% 
#   hchart() %>% 
#   hc_add_theme(thm)
```

### Sales by State

```{r}
data("USArrests", package = "datasets")
data("usgeojson")

USArrests <- USArrests %>%
  mutate(state = rownames(.))

n <- 4
colstops <- data.frame(
  q = 0:n/n,
  c = substring(viridis(n + 1), 0, 7)) %>%
  list.parse2()

highchart() %>%
  hc_add_series_map(usgeojson, USArrests, name = "Sales",
                    value = "Murder", joinBy = c("woename", "state"),
                    dataLabels = list(enabled = TRUE,
                                      format = '{point.properties.postalcode}')) %>%
  hc_colorAxis(stops = colstops) %>%
  hc_legend(valueDecimals = 0, valueSuffix = "%") %>%
  hc_mapNavigation(enabled = TRUE) %>%
  hc_add_theme(thm)
```

Column {.tabset data-width=400}
-----------------------------------------------------------------------

### Sales by Category

```{r, fig.keep='none'}
data("Groceries", package = "arules")
dfitems <- tbl_df(Groceries@itemInfo)

set.seed(10)

dfitemsg <- dfitems %>%
  mutate(category = gsub(" ", "-", level1),
         subcategory = gsub(" ", "-", level2)) %>%
  group_by(category, subcategory) %>% 
  summarise(sales = n() ^ 3 ) %>% 
  ungroup() %>% 
  sample_n(31)

tm <- treemap(dfitemsg, index = c("category", "subcategory"),
              vSize = "sales", vColor = "sales",
              type = "value", palette = rev(viridis(6)))

highchart() %>% 
  hc_add_series_treemap(tm, allowDrillToNode = TRUE,
                        layoutAlgorithm = "squarified") %>% 
  hc_add_theme(thm)
```

### Best Sellers

```{r}
set.seed(2)

nprods <- 10

dfitems %>% 
  sample_n(nprods) %>% 
  .$labels %>% 
  rep(times = sort(sample( 1e4:2e4, size = nprods), decreasing = TRUE)) %>% 
  factor(levels = unique(.)) %>% 
  hchart(showInLegend = FALSE, name = "Sales", pointWidth = 10) %>% 
  hc_add_theme(thm) %>% 
  hc_chart(type = "bar")
  
```