---
title: "Cat QA"
author: "Rotblauer"
output: 
  html_document: 
    includes:
      in_header: metaS.html
---



```{r setup, include=FALSE}
    # includes:
    #    in_header: metaQA.html
    # orientation: columns
    # vertical_layout: scroll
library(highcharter)
library(dplyr)
library(viridisLite)
library(treemap)
library(flexdashboard)
library(sp)
library(rworldmap)
library(rgeos)
library(maptools)
library(stringi)
library(maps)
library(plotly)
library(jsonlite)
# knitr::opts_chunk$set(fig.width=6, fig.height=10) 


thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )


load("./parsed/loc.Rdata")
# save(loc,file ="./parsed/loc.trim.Rdata" )

```

### Cat accuracy 

```{r include=TRUE}
# loc$accuracy < 10000
def = 0.75
sub = runif(length(loc$lon))
# loc = loc[sub < def , ]
summary(loc$accuracy)

p <- plot_ly(x = loc$accuracy,
type = "histogram") 

layout(p, 
       yaxis = list(type = "log"))

loc = loc[loc$accuracy < 1000 , ]

p <- plot_ly(x = loc$accuracy,
type = "histogram") 

layout(p, 
       yaxis = list(type = "log"))


speedAcc=loc$speed/loc$accuracy
speedAcc=speedAcc[is.finite(speedAcc)]
summary(speedAcc)
p <- plot_ly(x = speedAcc,
type = "histogram") 

layout(p, 
       yaxis = list(type = "log"))


```
