---
title: "Cat tracks stat cats"
author: "Rotblauer"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    social: menu
    source_code: embed
    includes:
       in_header: meta.html
---

```{r setup, include=FALSE}
library(highcharter)
library(dplyr)
library(viridisLite)
library(treemap)
library(flexdashboard)
library(sp)
library(rworldmap)
library(rgeos)
library(maptools)
library(stringi)
library(maps)
library(plotly)

data("usgeojson")
data("uscountygeojson")
data("county.fips")
data(worldgeojson, package = "highcharter")


thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )

latlong2state <- function(pointsDF) {
    # Prepare SpatialPolygons object with one SpatialPolygon
    # per state (plus DC, minus HI & AK)
    states <- map('state', fill=TRUE, col="transparent", plot=FALSE)
    IDs <- sapply(strsplit(states$names, ":"), function(x) x[1])
    states_sp <- map2SpatialPolygons(states, IDs=IDs,
                     proj4string=CRS("+proj=longlat +datum=WGS84"))

    # Convert pointsDF to a SpatialPoints object 
    pointsSP <- SpatialPoints(pointsDF, 
                    proj4string=CRS("+proj=longlat +datum=WGS84"))

    # Use 'over' to get _indices_ of the Polygons object containing each point 
    indices <- over(pointsSP, states_sp)

    # Return the state names of the Polygons object containing each point
    stateNames <- sapply(states_sp@polygons, function(x) x@ID)
    stri_trans_totitle(stateNames[indices])
}

coords2country = function(points)
{  
  countriesSP <- getMap(resolution='low')
  #countriesSP <- getMap(resolution='high') #you could use high res map from rworldxtra if you were concerned about detail

  # convert our list of points to a SpatialPoints object

  # pointsSP = SpatialPoints(points, proj4string=CRS(" +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"))

  #setting CRS directly to that from rworldmap
  pointsSP = SpatialPoints(points, proj4string=CRS(proj4string(countriesSP)))  


  # use 'over' to get indices of the Polygons object containing each point 
  indices = over(pointsSP, countriesSP)

  # return the ADMIN names of each country
  # indices$ADMIN  
  indices$ISO3 # returns the ISO3 code
  #indices$continent   # returns the continent (6 continent model)
  #indices$REGION   # returns the continent (7 continent model)
}

latlong2county <- function(pointsDF) {
    # Prepare SpatialPolygons object with one SpatialPolygon
    # per county
    counties <- map('county', fill=TRUE, col="transparent", plot=FALSE)
    
    IDs <- sapply(strsplit(counties$names, ":"), function(x) x[1])
    counties_sp <- map2SpatialPolygons(counties, IDs=IDs,
                     proj4string=CRS("+proj=longlat +datum=wgs84"))

    # Convert pointsDF to a SpatialPoints object 
    pointsSP <- SpatialPoints(pointsDF, 
                    proj4string=CRS("+proj=longlat +datum=wgs84"))

    # Use 'over' to get _indices_ of the Polygons object containing each point 
    indices <- over(pointsSP, counties_sp)

    # Return the county names of the Polygons object containing each point
    countyNames <- sapply(counties_sp@polygons, function(x) x@ID)
    countyNames[indices]
}



```



```{r init, eval=FALSE,include=FALSE}
library(jsonlite)


latMax = 39.773
latMin = 37.5205
lonMax = -89.149
lonMin = -91.4015


con_in <-
  file("~/Go/src/github.com/rotblauer/tileTester2/out.json.gz")

# con_in <-
#   file("~/Go/src/github.com/rotblauer/tileTester2/test.notes.json.gz")

con_out <- file(tmp <- "tmp.Rdata", open = "wb")

stream_in(
  con_in,
  handler = function(df) {
    # df <- dplyr::filter(df, distance > 1000)
    # df <- dplyr::mutate(df, delta = dep_delay - arr_delay)
    loc = do.call(rbind.data.frame, df$geometry$coordinates)

    colnames(loc) = c("lon", "lat")
    loc$elevation = df$properties$Elevation
    loc$note = df$properties$Notes
    loc$name = df$properties$Name
    loc$time = df$properties$Time
    loc$unixTime = df$properties$UnixTime
    loc$speed = df$properties$Speed
    loc$pressure = df$properties$Pressure
    loc$activity = df$properties$Activity
    print(colnames(loc))
    colnames(loc) = c(
      "lon",
      "lat",
      "elevation",
      "Notes",
      "Name",
      "Time",
      "UnixTime",
      "Speed",
      "Pressure",
      "Activity"
    )
 
    stream_out(loc, con_out, pagesize = 1000)
  },
  pagesize = 200000
)
close(con_out)
loc <- stream_in(file(tmp), pagesize = 2000000)

# test= stream_in(file("~/Go/src/github.com/rotblauer/tileTester2/test.notes.json.gz"), pagesize = 2000000)

save(loc, file = "loc.tmp.Rdata")
locCoords=loc[, c(1, 2)]
save(locCoords,file="locCoords.tmp.Rdata")

```

```{r asi, eval=FALSE,include=FALSE}
load("locCoords.tmp.Rdata")
# pointsDF=locCoords[, c(1, 2)]
locCoords$state = latlong2state(locCoords[, c(1, 2)])
# locCoords$country = coords2country(locCoords[, c(1, 2)])
locCoords$countyName = latlong2county(locCoords[, c(1, 2)])

save(locCoords, file = "locCoords.Rdata")

```

```{r  eval=FALSE,include=FALSE}
load("locCoords.Rdata")
load("loc.tmp.Rdata")
loc = cbind(loc, locCoords)

save(loc, file = "loc.Rdata")

   # loc <- filter(loc, lat < latMax &
   #                  lat > latMin) %>% filter(lon > lonMin &
   #                                             lon < lonMax)



```

Column {data-width=800}
-----------------------------------------------------------------------

```{r}

load("loc.Rdata")

```

<!-- county ="missouri,st louis|missouri,st louis city" -->

<!-- stl=grepl(county,loc$countyName) -->

<!-- stlLoc=loc[stl,] -->

<!-- ``` -->

<!-- ### Cats by STL cats - `r length(stlLoc$lon)` total tracks -->

<!-- ```{r} -->


<!--     plot_ly( -->
<!--       x =  stlLoc$lon, -->
<!--       y =  stlLoc$lat, -->
<!--       type = "scattergl", -->
<!--       mode = "markers" -->
<!--     ) -->

<!--     # , -->
<!--     #   color = "blue", -->
<!--     #   marker = list(opacity = .75, size = 2) -->

<!-- ``` -->




<!-- ### Cats by World - `r length(loc$lon)` total tracks -->

<!-- ```{r} -->
<!-- #  -->
<!-- #  -->
<!-- #  -->
<!-- # perCountry=as.data.frame(table(loc$country)) -->
<!-- # colnames(perCountry)=c("country","count") -->
<!-- # perCountry$country=as.character(perCountry$country) -->
<!-- # perCountry$Log10count=log10(perCountry$count) -->
<!-- #  -->
<!-- # world=highchart(type = "map") %>% -->
<!-- #   hc_add_series_map(map = worldgeojson, df = perCountry, value = "count", joinBy = c("iso3","country")) %>% -->
<!-- #   hc_colorAxis(stops = color_stops()) %>% -->
<!-- #   hc_mapNavigation(enabled = TRUE) %>% -->
<!-- #   hc_tooltip(useHTML = TRUE, headerFormat = "", -->
<!-- #   pointFormat = "This is {point.name} and has 10^{point.count} tracks") -->

<!-- ``` -->

```{r}
locC = merge(
loc,
county.fips,
by.x = "countyName",
by.y = "polyname")

perCounty=as.data.frame(table(locC$fips))
colnames(perCounty)=c("county","count")
perCounty$county=as.character(perCounty$county)
perCounty$count=log10(perCounty$count)


```


### Cats by County - `r length(locC$lon)` total tracks

```{r}




c=highchart() %>%
  hc_add_series_map(uscountygeojson, perCounty, name = "Cats",
                    value = "count", joinBy = c("fips", "county"))%>%
  hc_colorAxis(stops = color_stops()) %>%
  hc_title(text = "Log10 counts of cats by county") %>% 
  hc_mapNavigation(enabled = TRUE) %>%
  hc_tooltip(useHTML = TRUE, headerFormat = "",
  pointFormat = "This is {point.name} and has 10^{point.count} tracks")
c

htmlwidgets::saveWidget(widget = c, file = "./map.html")

webshot::webshot(url = "./map.html",
                 file = "./map.png")



```


### Cats by United

```{r}

perState=as.data.frame(table(loc$state))
colnames(perState)=c("state","count")
perState$state=as.character(perState$state)
perState$count=log10(perState$count)

highchart() %>%
  hc_add_series_map(usgeojson, perState, name = "Cats",
                    value = "count", joinBy = c("woename", "state")) %>%
  hc_colorAxis(stops = color_stops()) %>%
  hc_title(text = "Log10 counts of cats by State") %>% 
  hc_mapNavigation(enabled = TRUE) %>%
  hc_tooltip(useHTML = TRUE, headerFormat = "",
  pointFormat = "This is {point.name} and has 10^{point.count} tracks")

```


Column {.tabset data-width=400}
-----------------------------------------------------------------------

### Cat activities

```{r, fig.keep='none'}
dfitems <- as.data.frame(table(loc[nchar(loc$Activity)>0,c("Activity")]))

tm=treemap(dfitems, #Your data frame object
        index=c("Var1"),  #A list of your categorical variables
        vSize = "Freq",  #This is your quantitative variable
        type="index", #Type sets the organization and color scheme of your treemap
        palette =  rev(viridis(6)),  #Select your color palette from the RColorBrewer presets or make your own.
        title="Cat activities", #Customize your title
        fontsize.title = 14 #Change the font size of the title
        )

highchart() %>% 
  hc_add_series_treemap(tm, allowDrillToNode = TRUE,
                        layoutAlgorithm = "squarified") %>% 
  hc_add_theme(thm)
```



### Cat People

```{r, fig.keep='none'}

dfitems <- as.data.frame(table(loc[,c("Name")]))

tm=treemap(dfitems,
        index=c("Var1"),
        vSize = "Freq",
        type="index",
        palette =  rev(viridis(6)),
        title="People with cats",
        fontsize.title = 14
        )

highchart() %>%
  hc_add_series_treemap(tm, allowDrillToNode = TRUE,
                        layoutAlgorithm = "squarified") %>%
  hc_add_theme(thm)
```
