---
title: "cats"
author: "JL"
date: "9/23/2017"
output: 
  html_document: 
    keep_md: yes
---

```{r clusts, eval=TRUE}
clustNums =10
cols <- paste0("clust",c(1:clustNums))
```

```{r setup, include=FALSE,eval=FALSE}
library(jsonlite)


system.time(x <- fromJSON("~/Go/src/github.com/rotblauer/tileTester2/out.json"))
loc=data.frame()
loc = do.call(rbind.data.frame, x$features$geometry$coordinates)
loc$elevation =x$features$properties$Elevation
colnames(loc) =c("lon","lat","elevation")

save(loc,file = "loc.RData")
```

```{r setupClust, include=FALSE,eval=FALSE}
library(dplyr)
library(ClusterR)
load("loc.RData")

loc_gc <- filter(loc, lat < 38.6490 & lat > 38.6465) %>% filter(elevation>100&lon > -90.2775& lon < -90.275)
loc_gc =loc_gc[complete.cases(loc_gc), ]

clust =loc_gc
clust= scale(clust) 
d  <- dist(clust) 
clusStats = data.frame(K=numeric(),WithinSS=numeric())

# opt =Optimal_Clusters_KMeans(clust, max_clusters = 15, plot_clusters = T,
#                               
#                               criterion = 'distortion_fK', fK_threshold = 0.85,
#                               
#                               initializer = 'optimal_init', tol_optimal_init = 0.2)
for(i in 1:clustNums){
  print(i)
  km_rc = KMeans_rcpp(clust, clusters = i, num_init = i, max_iters = 1000, 
                    
                    initializer = 'optimal_init', threads = 3, verbose = T)
  
  tmp=data.frame(km_rc$clusters)
  colnames(tmp)=c(cols[i])
  loc_gc=cbind(loc_gc,tmp)
  print(colnames(loc_gc))
  tmp2 = data.frame(K=c(i),WithinSS=c(mean(km_rc$between.SS_DIV_total.SS)))
  clusStats= rbind(clusStats,tmp2)
}


# loc_gc$clust =km$cluster
save(loc_gc,file = "loc_gc.RData")
save(clusStats,file = "clusStats.RData")

```



```{r p,warning=FALSE,echo=FALSE}
library(knitr)
library(rgl)
library(rglwidget)
knit_hooks$set(webgl = hook_webgl)
library(scatterplot3d)
library(MASS)
library(ggplot2)
library(akima)
theme_set(theme_bw(20))
t2 <- theme(
    axis.line = element_line(colour = "black"),
    axis.text = element_text(colour = "black"),
    axis.ticks = element_line(colour = "black"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    axis.text.x=element_text(angle=90,hjust=1)
)

load("./loc_gc.RData")
load("./clusStats.RData")
ggplot(loc_gc, aes(x = lon, y = lat,colour=elevation)) + geom_point()+ geom_density_2d()+t2
ggplot(loc_gc, aes(x = lon, y = elevation,colour=elevation)) + geom_point()+ geom_density_2d()+t2
ggplot(loc_gc, aes(x = lat, y = elevation,colour=elevation)) + geom_point()+ geom_density_2d()+t2



 ggplot(loc_gc, aes(x = lon, y = lat))+stat_density2d(aes(fill=..density..), geom="raster", contour=FALSE) +
  scale_fill_gradient2(low="blue", mid="white", high="black") +t2

 ggplot(clusStats, aes(x = clusStats$K, y = clusStats$WithinSS)) + geom_point()+t2

 
ggplot(loc_gc, aes(x = lon, y = lat,colour=clust5)) + geom_point()+ geom_density_2d()+t2
ggplot(loc_gc, aes(x = lon, y = elevation,colour=clust5)) + geom_point()+ geom_density_2d()+t2
ggplot(loc_gc, aes(x = lat, y = elevation,colour=clust5)) + geom_point()+ geom_density_2d()+t2

ggplot(loc_gc, aes(x = lon, y = lat,colour=as.factor(clust5))) + geom_point()+ t2
ggplot(loc_gc, aes(x = lon, y = elevation,colour=as.factor(clust5))) + geom_point()+ t2
ggplot(loc_gc, aes(x = lat, y = elevation,colour=as.factor(clust5))) + geom_point()+ t2

 
# loc_gcP =loc_gc[which(loc_gc$clust5!=6),]
mfrow3d(nr = 2, nc = 1)
plot3d(loc_gc$lon, loc_gc$lat, loc_gc$elevation,col =loc_gc$clust5, size=2 )
# plot3d(loc_gcP$lon, loc_gcP$lat, loc_gcP$elevation,col =loc_gcP$clust5 )

rglwidget(height = 1000, width = 1000)


# dir.create("animation")
# for (i in 1:90) {
#   view3d(userMatrix=rotationMatrix(2*pi * i/90, 1, -1, -1))
#   rgl.snapshot(filename=paste("animation/frame-",
#     sprintf("%03d", i), ".png", sep=""))
# }
# convert -delay 5 -loop 0 frame*.png animated.gif
```

