---
title: "cats"
author: "JL"
date: "9/23/2017"
output: 
  html_document: 
    keep_md: yes
---

```{r clusts, eval=TRUE}
library(ClusterR)
library(knitr)
library(rgl)
library(rglwidget)
knit_hooks$set(webgl = hook_webgl)
library(scatterplot3d)
library(ggplot2)
library(sm)
library(dplyr)


clustME <- function(numberOfClusters,clust,loc_gc) {
  cols <- paste0("clust",c(1:numberOfClusters))
  clusStats = data.frame(K=numeric(),WithinSS=numeric())
  i=1
  for(i in 1:numberOfClusters){
    print(i)
    km_rc = KMeans_rcpp(clust, clusters = i, num_init = 100, max_iters = 1000, 
                      
                      initializer = 'optimal_init', threads = 4, verbose = T)
    
    tmp=data.frame(km_rc$clusters)
    colnames(tmp)=c(cols[i])
    loc_gc=cbind(loc_gc,tmp)
    print(colnames(loc_gc))
    tmp2 = data.frame(K=c(i),WithinSS=c(mean(km_rc$between.SS_DIV_total.SS)))
    clusStats= rbind(clusStats,tmp2)
  }
  save(clusStats,file = "clusStats.RData")

  return(loc_gc)
}
```

```{r setup, include=FALSE,eval=FALSE}
library(jsonlite)


system.time(x <- fromJSON("~/Go/src/github.com/rotblauer/tileTester2/out.json"))
loc=data.frame()
loc = do.call(rbind.data.frame, x$features$geometry$coordinates)
loc$elevation =x$features$properties$Elevation
loc$accuracy =x$features$properties$Accuracy

colnames(loc) =c("lon","lat","elevation")

save(loc,file = "loc.RData")
```

```{r setupClust, include=FALSE,eval=FALSE}
load("loc.RData")
# loc =loc[which(loc$accuracy>0&loc$accuracy<=10),]
loc_gc <- filter(loc, lat < 38.6490 & lat > 38.6465) %>% filter(elevation>100&lon > -90.2785& lon < -90.274)

loc_gc =loc_gc[complete.cases(loc_gc), ]

loc_gc =clustME(numberOfClusters = 6,clust =scale(loc_gc[,c("lon","lat","elevation")]),loc_gc = loc_gc )


loc_gca <- filter(loc,lat < 38.6477 & lat > 38.6473) %>% filter(elevation>160.1710&lon > -90.2759& lon < -90.2757&elevation<175.171)

loc_gca =clustME(numberOfClusters = 10,clust =scale(loc_gca[,c("lon","lat","elevation")]) ,loc_gc = loc_gca)


# loc_gc$clust =km$cluster
save(loc_gc,file = "loc_gc.RData")
save(loc_gca,file = "loc_gca.RData")


```



```{r p,warning=FALSE,echo=FALSE}

theme_set(theme_bw(20))
t2 <- theme(
    axis.line = element_line(colour = "black"),
    axis.text = element_text(colour = "black"),
    axis.ticks = element_line(colour = "black"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    axis.text.x=element_text(angle=90,hjust=1)
)
# load("./clust.RData")
load("./loc_gc.RData")
load("./loc_gca.RData")

load("./clusStats.RData")


ggplot(loc_gc, aes(x = lon, y = lat,colour=elevation)) + geom_point()+ geom_density_2d()+t2
ggplot(loc_gc, aes(x = lon, y = elevation,colour=elevation)) + geom_point()+ geom_density_2d()+t2
ggplot(loc_gc, aes(x = lat, y = elevation,colour=elevation)) + geom_point()+ geom_density_2d()+t2



 ggplot(loc_gc, aes(x = lon, y = lat))+stat_density2d(aes(fill=..density..), geom="raster", contour=FALSE) +
  scale_fill_gradient2(low="blue", mid="white", high="black") +t2


 opt =Optimal_Clusters_KMeans(loc_gc[,c("lon","lat","elevation")], max_clusters = 15, plot_clusters = T,

                              criterion = 'distortion_fK', fK_threshold = 0.85,

                              initializer = 'optimal_init', tol_optimal_init = 0.2)
 
 
ggplot(loc_gc, aes(x = lon, y = lat,colour=clust5)) + geom_point()+ geom_density_2d()+t2
ggplot(loc_gc, aes(x = lon, y = elevation,colour=clust5)) + geom_point()+ geom_density_2d()+t2
ggplot(loc_gc, aes(x = lat, y = elevation,colour=clust5)) + geom_point()+ geom_density_2d()+t2


 
ggplot(loc_gc, aes(x = lon, y = lat,colour=clust5)) +  geom_density_2d()+t2
ggplot(loc_gc, aes(x = lon, y = elevation,colour=clust5)) +  geom_density_2d()+t2
ggplot(loc_gc, aes(x = lat, y = elevation,colour=clust5)) + geom_density_2d()+t2



clusterC = sort(unique(loc_gc$clust5))
for (c in clusterC) {
tp = loc_gc[which(loc_gc$clust5 == c),]
gp = ggplot(tp, aes(x = lon, y = lat, colour = clust5)) + geom_point() + geom_density_2d() +
t2 + ggtitle(label = paste("cluster=", c,"n=",length(tp$lon)))
print(gp)
gp = ggplot(tp, aes(x = lon, y = elevation, colour = clust5)) + geom_point() + geom_density_2d() +
t2 + ggtitle(label = paste("cluster=", c,"n=",length(tp$lon)))
print(gp)
gp = ggplot(tp, aes(x = lat, y = elevation, colour = clust5)) + geom_point() + geom_density_2d() +
t2 + ggtitle(label = paste("cluster=", c,"n=",length(tp$lon)))
print(gp)
gp = ggplot(tp, aes(x = lon, y = lat, colour = clust5)) +  geom_density_2d() +
t2 + ggtitle(label = paste("cluster=", c,"n=",length(tp$lon)))
print(gp)
gp = ggplot(tp, aes(x = lon, y = elevation, colour = clust5)) +  geom_density_2d() + t2 + ggtitle(label = paste("cluster=", c,"n=",length(tp$lon)))
print(gp)
gp = ggplot(tp, aes(x = lat, y = elevation, colour = clust5)) + geom_density_2d() + t2 + ggtitle(label = paste("cluster=", c,"n=",length(tp$lon)))
print(gp)


}


 opt =Optimal_Clusters_KMeans(scale(loc_gca[c("lon","lat","elevation")]), max_clusters = 15, plot_clusters = T,

                              criterion = 'distortion_fK', fK_threshold = 0.85,

                              initializer = 'optimal_init', tol_optimal_init = 0.2)

ggplot(loc_gca, aes(x = lon, y = lat,colour=clust5)) + geom_point()+ geom_density_2d()+t2
ggplot(loc_gca, aes(x = lon, y = elevation,colour=clust5)) + geom_point()+ geom_density_2d()+t2
ggplot(loc_gca, aes(x = lat, y = elevation,colour=clust5)) + geom_point()+ geom_density_2d()+t2

ggplot(loc_gca, aes(x = lon, y = lat,colour=clust5)) + geom_density_2d()+t2
ggplot(loc_gca, aes(x = lon, y = elevation,colour=clust5)) +  geom_density_2d()+t2
ggplot(loc_gca, aes(x = lat, y = elevation,colour=clust5)) + geom_density_2d()+t2


# 
# 
# 
# library(hexbin)
# h <- hexbin(loc_gca)
# plot(loc_gca)
# 
# hexbinplot(lat~lon, data=loc_gca, colramp=rf, trans=log, inv=exp)
# library(gplots)
# h2 <- hist2d(x = loc_gca$lon,y = loc_gca$lat)
# scatterplot3d(loc_gca[,c("lon","lat","elevation")], highlight.3d = TRUE, pch = 20)

# p <- ggplot(loc_gca, aes(lon,lat))
# h3 <- p + stat_bin2d(bins=25) + scale_fill_gradientn(colours=r, trans="log")
# h3



load("loc.RData")

loc_gca <- filter(loc,lat < 38.6477 & lat > 38.6473) %>% filter(elevation>155.1710&lon > -90.2759& lon < -90.2757&elevation<175.171)



library(RColorBrewer)
rf <- colorRampPalette(rev(brewer.pal(11,'Spectral')))
r <- rf(64)
library(MASS)
n =500
h1 <- hist(loc_gca$lon, breaks=n, plot=F)
h2 <- hist(loc_gca$lat, breaks=n, plot=F)
top <- max(h1$counts, h2$counts)

k <- kde2d(loc_gca$lon, loc_gca$lat, n=n)

oldpar <- par()
par(mar=c(3,3,1,1))
layout(matrix(c(2,0,1,3),2,2,byrow=T),c(3,1), c(1,3))
image(k, col=r) #plot the image
par(mar=c(0,2,1,0))
barplot(h1$counts, axes=F, ylim=c(0, top), space=0, col='red')
par(mar=c(2,0,0.5,1))
barplot(h2$counts, axes=F, xlim=c(0, top), space=0, col='red', horiz=T)

```

```{r 3d, include=FALSE,eval=FALSE}

load("./loc_gca.RData")

# loc_gca$elevationScaled = scale(loc_gca$elevation,center = TRUE,scale = TRUE)
loc_gca$fakeEl = rnorm(n = length(loc_gca$lon))
# loc_gca$fakeEl =loc_gca$fakeEl+abs(min(loc_gca$fakeEl))+1
# sm.density(loc_gca[,c("lon","lat","elevation")],alpha=.2)
# sm.density(loc_gca[,c("lon","lat","fakeEl")],alpha=.001)
filt = .5

loc_gca =loc_gca[which(abs(loc_gca$fakeEl)<filt),]

elplot = "fakeEl"

animate ="animation4"
dir.create(animate)
lims =seq(from = min(loc_gca[,c(elplot)]),to=max(loc_gca[,c(elplot)]),length.out = 42)
r3dDefaults$windowRect <- c(0,0,1200,1200)
num =0
for(l in rev(lims)) {
  sub = loc_gca[, c("lon", "lat", elplot)]
  sm.density(sub, alpha = .2, zlim = c(min(loc_gca[, c(elplot)]), l))
  view3d(userMatrix = rotationMatrix(0, 0, 0, 1))
  rgl.snapshot(filename = paste(animate, "/alob-",
  sprintf("%03d", num), ".png", sep = ""))
  
  if (num %% 10 == 0) {
  for (i in 1:90) {
  view3d(userMatrix = rotationMatrix(2 * pi * i / 90, 1,-1,-1))
  # view3d(userMatrix=rotationMatrix(-1, -2*pi * 90,-1 ,-1))
  rgl.snapshot(filename = paste(animate, "/alob-",
  sprintf("%03d", num), ".png", sep = ""))
  num = num + 1
  }
  
  }
  rgl.close()
  
  num = num + 1
}

for(l in rev(lims)) {
  sm.density(loc_gca[, c("lon", "lat", elplot)], alpha = .2, zlim = c(min(loc_gca[, c(elplot)]), l))
  view3d(userMatrix = rotationMatrix(1,-1, 0, 1))
  rgl.snapshot(filename = paste(animate, "/blob-",
  sprintf("%03d", num), ".png", sep = ""))
  if (num %% 10 == 0) {
  for (i in 1:90) {
  view3d(userMatrix = rotationMatrix(2 * pi * i / 90, 1,-1,-1))
  # view3d(userMatrix=rotationMatrix(-1, -2*pi * 90,-1 ,-1))
  rgl.snapshot(filename = paste(animate, "/blob-",
  sprintf("%03d", num), ".png", sep = ""))
  num = num + 1
  }
  
  }
  rgl.close()
  num = num + 1
}

  sm.density(loc_gca[,c("lon","lat",elplot)],alpha=.2,zlim=c(min(loc_gca[,c(elplot)]),l))



# 
# library(ks)
# data(unicef)
# unicef$bah=rnorm(n = length(unicef$`Under-5`))
# H.scv <- Hscv(x=unicef)
# fhat <- kde(x=unicef, H=H.scv)
# 
# loc_gcad =loc_gca[,c("lon","lat","elevation")]
# H.scv <- Hscv(x=loc_gcad)
# fhat <- kde(x=loc_gcad, H=H.scv)
#             
# 
# # 
# 
# # loc_gcas=scale(loc_gca[,c("lon","lat","elevation")])
# mfrow3d(nr = 1, nc = 1)
# # sm.density(loc_gcas)
# sm.density(loc_gca[,c("lat","fakeEl","lon")])
# sm = sm.density(loc_gca[,c("lat","elevation","lon")])
# scatter2D(colvar = O2sat, x = loc$lon, y = loc$lat, pch = 16, add = TRUE, cex = 2, clab = "%")
# sm.density(loc_gca[,c("lon","elevationScaled","lat")])
# # sm.density(loc_gca[,c("lonX","latX","fakeEl")])
# rglwidget(height = 1000, width = 1000)
# # loc_gcP =loc_gc[which(loc_gc$clust5!=6),]
# # 

# library(hexbin)
# library(RColorBrewer)
# bin<-hexbin(loc_gca$lon, loc_gca$lat, xbins=50)
# my_colors=colorRampPalette(rev(brewer.pal(11,'Spectral')))
# plot(bin, main="" , colramp=my_colors  ) 

# z =kde3d(x = loc_gca$lon,y = loc_gca$lat,z = loc_gca$elevation)
 # plot3d(z$x, z$y, z$z,col =z$d, size=2 )
# # plot3d(loc_gc$lon, loc_gc$lat, loc_gc$elevation,col =loc_gc$clust2, size=2 )
# # # plot3d(loc_gcP$lon, loc_gcP$lat, loc_gcP$elevation,col =loc_gcP$clust5 )
# # 
# # rglwidget(height = 1000, width = 1000)
# 
# 


# 


# https://hackernoon.com/learn-blockchains-by-building-one-117428612f46

# mfrow3d(nr = 1, nc = 1)
# plot3d(loc_gca$lon, loc_gca$lat, loc_gca$elevation,col =loc_gca$clust5, size=2 )
# rglwidget(height = 1000, width = 1000)



# 

# mfrow3d(nr = 1, nc = 1)
# tp =loc_gc[which(loc_gc$clust5 == 4),]
# t =plot3d(tp$lon,
# tp$lat,
# tp$elevation,
# col = tp$clust5,
# size = 2)
# print(t)
# # plot3d(loc_gcP$lon, loc_gcP$lat, loc_gcP$elevation,col =loc_gcP$clust5 )
# 
# rglwidget(height = 1000, width = 1000)


# convert -delay 10 -loop 0 frame*.png animated.gif
# convert -delay 15 -loop 0 *.png animated.gif
```

